#define BAIYANG baiyang
#define SUPPORT_ION 
#define LINUX 
#define PVR_BUILD_DIR "mt8173"
#define PVR_BUILD_TYPE "debug"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SUPPORT_RGX 1
#define PVR_SECURE_HANDLES 
#define DISPLAY_CONTROLLER dc_fbdev
#define DEBUG 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define DEBUG_LINUX_MEM_AREAS 
#define DEBUG_LINUX_MMAP_AREAS 
#define DEBUG_BRIDGE_KM 
#define DEBUG_HANDLEALLOC_KM 
#define RGXFW_ALIGNCHECKS 
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_4.29.2.51.h"
#define RGX_BNC_CONFIG_KM_HEADER "configs/rgxconfig_km_4.V.2.51.h" 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEED_PVR_DPF 
#define CACHEFLUSH_TYPE CACHEFLUSH_GENERIC
#define SUPPORT_INSECURE_EXPORT 
#define SUPPORT_SECURE_EXPORT 
//#define SUPPORT_GPUTRACE_EVENTS 
#define SUPPORT_DISPLAY_CLASS 1 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define LDM_PLATFORM 
#define PVRSRV_ENABLE_PROCESS_STATS 
#define PVR_RI_DEBUG 1 
#define PVR_LINUX_PYSMEM_MAX_POOL_PAGES 10240
#define PVR_LINUX_VMALLOC_ALLOCATION_THRESHOLD  16384 
#define ANDROID 
#define SUPPORT_ION 
#define PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC 
#define PVR_ANDROID_ION_HEADER "../drivers/staging/android/ion/ion.h"
#define PVR_ANDROID_ION_PRIV_HEADER "../drivers/staging/android/ion/ion_priv.h"
#define PVR_ANDROID_ION_USE_SG_LENGTH 
